# encoding: utf-8

'''🛂 EDRN DICOM Validation: report splitter.

Split a .csv file generated by validate-dicom-files into separate files for each site.

Usage: `split-report.py <report.csv>`

Example:

`split-report.py report.csv`

This will create the following files:

report_site_1.csv
report_site_2.csv
...
report_site_n.csv

The files are created in the current directory.
'''

import csv, os, argparse, io

# Header should stay the same for every site
_header_row = ['Site ID', 'Event ID', 'File Name', 'Score', 'Findings', 'Details']

# Mapping of site ID to a double containing the file handle and the CSV writer
_handles: dict[str, tuple[io.TextIOBase, csv.writer]] = {}


def _get_io(site_id: str) -> tuple[io.TextIOBase, csv.writer]:
    if site_id in _handles: return _handles[site_id]
    site_report_file = f'report_site_{site_id}.csv'
    file_handle = open(site_report_file, 'w', newline='')
    writer = csv.writer(file_handle)
    writer.writerow(_header_row)
    _handles[site_id] = (file_handle, writer)
    return file_handle, writer


def split_report(report_file: str):
    with open(report_file, 'r') as io:
        reader = csv.reader(io)
        for row in reader:
            if row[0] == 'Site ID': continue
            site_id, event_id, file_name, score, findings, details = row
            _, writer = _get_io(site_id)
            writer.writerow([site_id, event_id, file_name, score, findings, details])
    for file_handle, _ in _handles.values():
        file_handle.close()


def main():
    parser = argparse.ArgumentParser(description='Split a .csv file generated by validate-dicom-files into separate files for each site.')
    parser.add_argument('report_file', type=str, help='The .csv file to split')
    args = parser.parse_args()
    split_report(args.report_file)


if __name__ == '__main__':
    main()
