# encoding: utf-8

'''🛂 EDRN DICOM Validation: validators.'''


from ._experimental import ExperimentalModalityValidator, ExperimentalManufacturerValidator  # noqa: F401
from ._core import (
    SeriesDescriptionValidator,
    StudyInstanceUIDValidator,
    SeriesInstanceUIDValidator,
    SeriesNumberValidator,
    InstanceNumberValidator,
    SOPClassUIDValidator,
    ModalityValidator,
    ManufacturerValidator,
    ModelNameValidator,
    SoftwareVersionsValidator,
    StudyDateValidator,
    ContentDateValidator,
    AcquisitionDateValidator,
    AcquisitionTimeValidator,
    ContentTimeValidator,
    RowsValidator,
    ColumnsValidator,
    SOPInstanceUIDValidator,
    BitsAllocatedValidator,
    BitsStoredValidator,
    HighBitValidator,
    PixelRepresentationValidator,
    PhotometricInterpretationValidator,
    WindowCenterValidator,
    WindowWidthValidator,
    PixelSpacingValidator,
    ImagePositionPatientValidator,
    ImageOrientationPatientValidator,
    ImageTypeValidator,
    SliceThicknessValidator,
    FrameOfReferenceUIDValidator,
)
from ._mr import SpacingBetweenSlicesValidator

VALIDATORS = [
    # These are experimental validators for testing and development purposes and should not be used in production:
    # ExperimentalModalityValidator(),
    # ExperimentalManufacturerValidator(),

    SeriesDescriptionValidator(),
    StudyInstanceUIDValidator(),
    SeriesInstanceUIDValidator(),
    SeriesNumberValidator(),
    InstanceNumberValidator(),
    SOPClassUIDValidator(),
    ModalityValidator(),
    ManufacturerValidator(),
    ModelNameValidator(),
    SoftwareVersionsValidator(),
    StudyDateValidator(),
    ContentDateValidator(),
    AcquisitionDateValidator(),
    AcquisitionTimeValidator(),
    ContentTimeValidator(),
    RowsValidator(),
    ColumnsValidator(),
    SOPInstanceUIDValidator(),
    BitsAllocatedValidator(),
    BitsStoredValidator(),
    HighBitValidator(),
    PixelRepresentationValidator(),
    PhotometricInterpretationValidator(),
    WindowCenterValidator(),
    WindowWidthValidator(),
    PixelSpacingValidator(),
    ImagePositionPatientValidator(),
    ImageOrientationPatientValidator(),
    ImageTypeValidator(),
    SliceThicknessValidator(),
    FrameOfReferenceUIDValidator(),
    SpacingBetweenSlicesValidator(),
]
